// src/profissional/section-2/svelte-three-gsap/src/components/ThreeCanvas.svelte
<script>
  import { onMount } from "svelte";
  import { initThree, initWorld } from "../three/setupScene";
  let canvas;

  onMount(() => {
    const { scene, camera, renderer } = initThree(canvas);
    initWorld({ scene, camera, renderer });

    function animate() {
      requestAnimationFrame(animate);
      renderer.render(scene, camera);
    }
    animate();
  });
</script>

<canvas bind:this={canvas} id="three-canvas"></canvas>

// src/profissional/section-2/react-gsap-three/src/components/ThreeCanvas.jsx
import { useEffect, useRef } from "react";
import { initThree } from "../three/setupScene";
import { initWorld } from "../three/setupScene";
// Padrao para setar o threejs e iniciar o mundo baseada na cena que quer

export default function ThreeCanvas() {
  const canvasRef = useRef();

  useEffect(() => {
    const { scene, camera, renderer } = initThree(canvasRef.current);
    initWorld(scene);

    function animate() {
      requestAnimationFrame(animate);
      renderer.render(scene, camera);
    }

    animate();
  }, []);

  return <canvas ref={canvasRef} />;
}
